### PR TITLE
doc stack v2

### PR DESCRIPTION
**Pull request by agardnerIT**
@Nexucis I believe this is what you mean [here](https://github.com/perses/website/pull/34#issuecomment-2345637887)

```
pip install -r requirements.txt
mkdocs serve -a "localhost:8000"
```

### CODE REVIEW

**Comment by Nexucis** [comment]
By looking at the files, yes I mean that. Thank you.

I tried to run the website and it seems I am missing something because when I tried the command I got that:

```bash
mkdocs serve -a "localhost:8000"

Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'material.extensions.emoji' (No module named 'material')
  in "/Users/ahusson/workspace/go/src/perses/website/mkdocs.yml", line 37, column 20
```

Probably I have an issue with my environment

**Comment by Nexucis** [comment]
but no idea what it is, rerunning the command to install the packages it tells me all requirements are satisfied.

```bash
 pip3 install -r requirements.txt --break-system-packages --user
Requirement already satisfied: mkdocs-multirepo-plugin in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from -r requirements.txt (line 1)) (0.8.3)
Requirement already satisfied: mkdocs-material==9.5.34 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from -r requirements.txt (line 2)) (9.5.34)
Requirement already satisfied: mike==2.1.3 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from -r requirements.txt (line 3)) (2.1.3)
Requirement already satisfied: babel~=2.10 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2.16.0)
Requirement already satisfied: colorama~=0.4 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: jinja2~=3.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (3.1.4)
Requirement already satisfied: markdown~=3.2 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (3.7)
Requirement already satisfied: mkdocs-material-extensions~=1.3 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: mkdocs~=1.6 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (1.6.1)
Requirement already satisfied: paginate~=0.5 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (0.5.7)
Requirement already satisfied: pygments~=2.16 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: pymdown-extensions~=10.2 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (10.9)
Requirement already satisfied: regex>=2022.4 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2024.9.11)
Requirement already satisfied: requests~=2.26 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2.32.3)
Requirement already satisfied: importlib-metadata in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mike==2.1.3->-r requirements.txt (line 3)) (8.5.0)
Requirement already satisfied: importlib-resources in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mike==2.1.3->-r requirements.txt (line 3)) (6.4.5)
Requirement already satisfied: pyparsing>=3.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mike==2.1.3->-r requirements.txt (line 3)) (3.1.4)
Requirement already satisfied: pyyaml>=5.1 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mike==2.1.3->-r requirements.txt (line 3)) (6.0.2)
Requirement already satisfied: pyyaml-env-tag in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mike==2.1.3->-r requirements.txt (line 3)) (0.1)
Requirement already satisfied: verspec in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mike==2.1.3->-r requirements.txt (line 3)) (0.1.0)
Requirement already satisfied: dacite<2.0.0,>=1.8.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-multirepo-plugin->-r requirements.txt (line 1)) (1.8.1)
Requirement already satisfied: python-slugify in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-multirepo-plugin->-r requirements.txt (line 1)) (8.0.4)
Requirement already satisfied: typing-inspect<0.9.0,>=0.8.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-multirepo-plugin->-r requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from jinja2~=3.0->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2.1.5)
Requirement already satisfied: click>=7.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (8.1.7)
Requirement already satisfied: ghp-import>=1.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: mergedeep>=1.3.4 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (1.3.4)
Requirement already satisfied: mkdocs-get-deps>=0.2.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: packaging>=20.5 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (24.1)
Requirement already satisfied: pathspec>=0.11.1 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (0.12.1)
Requirement already satisfied: watchdog>=2.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (5.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from requests~=2.26->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from requests~=2.26->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (3.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from requests~=2.26->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from requests~=2.26->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2024.8.30)
Requirement already satisfied: mypy-extensions>=0.3.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from typing-inspect<0.9.0,>=0.8.0->mkdocs-multirepo-plugin->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: typing-extensions>=3.7.4 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from typing-inspect<0.9.0,>=0.8.0->mkdocs-multirepo-plugin->-r requirements.txt (line 1)) (4.12.2)
Requirement already satisfied: zipp>=3.20 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from importlib-metadata->mike==2.1.3->-r requirements.txt (line 3)) (3.20.2)
Requirement already satisfied: text-unidecode>=1.3 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from python-slugify->mkdocs-multirepo-plugin->-r requirements.txt (line 1)) (1.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from ghp-import>=1.0->mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.2.0 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from mkdocs-get-deps>=0.2.0->mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (4.3.3)
Requirement already satisfied: six>=1.5 in /Users/ahusson/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.1->ghp-import>=1.0->mkdocs~=1.6->mkdocs-material==9.5.34->-r requirements.txt (line 2)) (1.16.0)
```

Also I am on a Mac M2 and I had to add a couple of flags because otherwise it didn't want to add the packages ...

**Comment by agardnerIT** [comment]
I've now got all the menu links transferred. I don't understand why you can't build. I'm running on an M2 Mac too.

**Comment by Nexucis** [comment]
awesome, thank you @agardnerIT !

Yeah no idea why, I will try again today. I would like to run it before merging it to at leat giving good feedback

**Comment by Nexucis** [comment]
ok I finally managed to make it works.

Looks awesome for a start ! I will merge it and will probably make some PRs to improve a bit what I am seeing.
Thanks !

**Comment by gmile** [comment]
As a passer by, excited about this :) Is there a place a new design can be previewed?

**Comment by Nexucis** [comment]
hey @gmile, thank you !

Unfortunately no there is no particular preview, excepting running the website locally. For a new design I think @agardnerIT have some ideas but other all it depends mainly on people and their imagination :).

**Comment by gmile** [comment]
I think I got mixed up the concepts of "new design" and... "new stack" which is what this PR is about 🙈

So the stack is changing to `mkdocs` and it can easily be ran locally now, but there won't be any new website design for now? I guess I understand now, thanks for clarifying 🙇

**Pull request merged**
